### ISSUE TITLE
Force landscape view for mobile

### ISSUE THREAD

**Issue by brandonkeao** [codefordenver/2017-Annual-Report#37]
As a [2017 annual report viewer]
I want to [only be able to view the report in landscape mode]
So that I can [experience the best format of the report]

Acceptance Criteria:
* Force landscape whenever device width is LESS THAN device height

**Comment by with-a-k** [comment]
I'll be handling this for the time being; could I be assigned to the issue?

**Comment by with-a-k** [comment]
It's resolved now (#43)
